# Generated by Django 6.0.1 on 2026-02-01 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('archive', models.BooleanField(default=False, verbose_name='Archivée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60, unique=True, verbose_name='Libellé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de carburant',
                'verbose_name_plural': 'Types de carburant',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60, unique=True, verbose_name='Libellé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de transmission',
                'verbose_name_plural': 'Types de transmission',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60, unique=True, verbose_name='Libellé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de véhicule',
                'verbose_name_plural': 'Types de véhicule',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('version', models.CharField(blank=True, max_length=80, verbose_name='Version')),
                ('annee_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année min')),
                ('annee_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année max')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='flotte.marque')),
            ],
            options={
                'verbose_name': 'Modèle',
                'verbose_name_plural': 'Modèles',
                'ordering': ['marque__nom', 'nom'],
                'unique_together': {('marque', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Gestionnaire'), ('user', 'Utilisateur')], default='user', max_length=20, verbose_name='Rôle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_flotte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chassis', models.CharField(help_text='Identifiant principal du véhicule (surtout en import sans immat.)', max_length=80, unique=True, verbose_name='Numéro de châssis')),
                ('annee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année')),
                ('couleur_exterieure', models.CharField(blank=True, max_length=60, verbose_name='Couleur extérieure')),
                ('couleur_interieure', models.CharField(blank=True, max_length=60, verbose_name='Couleur intérieure')),
                ('date_entree_parc', models.DateField(blank=True, null=True, verbose_name='Date entrée parc')),
                ('km_entree', models.PositiveIntegerField(default=0, verbose_name="Km à l'entrée")),
                ('kilometrage_actuel', models.PositiveIntegerField(default=0, verbose_name='Kilométrage actuel')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name="Prix d'achat (FCFA)")),
                ('origine_pays', models.CharField(blank=True, max_length=80, verbose_name="Pays d'origine")),
                ('etat_entree', models.CharField(blank=True, max_length=40, verbose_name="État à l'entrée")),
                ('statut', models.CharField(choices=[('parc', 'Au parc'), ('import', "En cours d'importation"), ('vendu', 'Vendu')], default='parc', max_length=20, verbose_name='Statut')),
                ('numero_immatriculation', models.CharField(blank=True, max_length=20, verbose_name='N° immatriculation')),
                ('date_premiere_immat', models.DateField(blank=True, null=True, verbose_name='Date première immatriculation')),
                ('consommation_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Consommation (L/100km)')),
                ('rejet_co2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rejet CO2 (g/km)')),
                ('puissance_fiscale', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puissance fiscale (CV)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='flotte.marque')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='flotte.modele')),
                ('type_carburant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='flotte.typecarburant')),
                ('type_transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='flotte.typetransmission')),
                ('type_vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='flotte.typevehicule')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-date_entree_parc', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reparation', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('kilometrage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('type_rep', models.CharField(blank=True, max_length=60, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('cout', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Coût (FCFA)')),
                ('prestataire', models.CharField(blank=True, max_length=120, verbose_name='Prestataire')),
                ('a_faire', models.BooleanField(default=False, verbose_name='À faire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparations', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Réparation',
                'verbose_name_plural': 'Réparations',
                'ordering': ['-date_reparation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locataire', models.CharField(max_length=200, verbose_name='Locataire')),
                ('type_location', models.CharField(max_length=60, verbose_name='Type')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('loyer_mensuel', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Loyer mensuel (FCFA)')),
                ('km_inclus_mois', models.PositiveIntegerField(blank=True, null=True, verbose_name='Km inclus / mois')),
                ('prix_km_supplementaire', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix km supplémentaire (FCFA)')),
                ('date_expiration_ct', models.DateField(blank=True, null=True, verbose_name='Date expiration visite technique (CT)')),
                ('date_expiration_assurance', models.DateField(blank=True, null=True, verbose_name='Date expiration assurance')),
                ('km_prochaine_vidange', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage prochaine vidange')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('a_venir', 'À venir'), ('termine', 'Terminé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ImportDemarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(max_length=80, verbose_name='Étape')),
                ('date_etape', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('statut_etape', models.CharField(blank=True, max_length=40, verbose_name='Statut étape')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_demarches', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Démarche import',
                'verbose_name_plural': 'Démarches import',
                'ordering': ['vehicule', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=80, verbose_name='Type')),
                ('numero', models.CharField(blank=True, max_length=60, verbose_name='Numéro')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name='Date émission')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='Date échéance')),
                ('disponible', models.BooleanField(default=False, verbose_name='Disponible')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Document véhicule',
                'verbose_name_plural': 'Documents véhicule',
                'ordering': ['vehicule', 'type_document'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('phase', models.CharField(blank=True, max_length=80, verbose_name='Phase')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Montant (FCFA)')),
                ('date_depense', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateField(verbose_name='Date vente')),
                ('acquereur', models.CharField(blank=True, max_length=200, verbose_name='Acquéreur')),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Prix vente (FCFA)')),
                ('km_vente', models.PositiveIntegerField(blank=True, null=True, verbose_name='Km à la vente')),
                ('garantie_duree', models.CharField(blank=True, max_length=80, verbose_name='Garantie')),
                ('etat_livraison', models.CharField(blank=True, max_length=40, verbose_name='État livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
            },
        ),
    ]
