# Generated by Django 6.0.1 on 2026-02-02 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='type_depense',
            field=models.CharField(choices=[('entretien', 'Entretien'), ('reparation', 'Réparation'), ('carburant', 'Carburant'), ('assurance', 'Assurance'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='modele',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='km_prochaine_vidange',
            field=models.PositiveIntegerField(blank=True, help_text='Km auquel effectuer la prochaine vidange (si hors location)', null=True, verbose_name='Kilométrage prochaine vidange'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='annee_min',
            field=models.PositiveIntegerField(default=2000, verbose_name='Année min'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='version',
            field=models.CharField(default='—', max_length=80, verbose_name='Version'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80, verbose_name='Numéro facture')),
                ('fournisseur', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('date_facture', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('montant', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Montant (FCFA)')),
                ('type_facture', models.CharField(blank=True, help_text='Ex: achat, réparation, assurance', max_length=60, verbose_name='Type')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_facture', '-id'],
            },
        ),
    ]
