# Generated by Django 6.0.1 on 2026-02-02 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0002_add_modele_archive_depense_type_facture_vehicule_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField(verbose_name='Date du rapport')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_rapport', models.CharField(choices=[('journalier', 'Rapport journalier flotte'), ('ca', "Document chiffre d'affaires"), ('autre', 'Autre')], default='journalier', max_length=20, verbose_name='Type')),
                ('fichier', models.FileField(help_text='Fichier PDF (rapport journalier, document CA)', max_length=255, upload_to='rapports/%Y/%m/', verbose_name='Fichier PDF')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rapport journalier',
                'verbose_name_plural': 'Rapports journaliers',
                'ordering': ['-date_rapport', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='modele',
            name='version',
            field=models.CharField(max_length=80, verbose_name='Version'),
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=120, verbose_name='Prénom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('permis_numero', models.CharField(blank=True, max_length=60, verbose_name='N° permis')),
                ('permis_date_expiration', models.DateField(blank=True, null=True, verbose_name='Date expiration permis')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducteur_flotte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conducteur',
                'verbose_name_plural': 'Conducteurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('vidange', 'Vidange'), ('courroie', 'Courroie de distribution'), ('pneus', 'Pneus'), ('filtres', 'Filtres (air, huile, habitacle)'), ('plaquettes', 'Plaquettes de frein'), ('batterie', 'Batterie'), ('autre', 'Autre')], default='vidange', max_length=20, verbose_name='Type')),
                ('date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('kilometrage_prevu', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage prévu')),
                ('date_effectuee', models.DateField(blank=True, null=True, verbose_name='Date effectuée')),
                ('kilometrage_effectue', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage effectué')),
                ('cout', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Coût (FCFA)')),
                ('prestataire', models.CharField(blank=True, max_length=120, verbose_name='Prestataire')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('effectue', 'Effectué')], default='a_faire', max_length=20, verbose_name='Statut')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_prevue', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReleveCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField(verbose_name='Date du relevé')),
                ('kilometrage', models.PositiveIntegerField(verbose_name='Kilométrage')),
                ('litres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Litres')),
                ('montant_fcfa', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Montant (FCFA)')),
                ('prix_litre', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Prix au litre (FCFA)')),
                ('lieu', models.CharField(blank=True, max_length=120, verbose_name='Lieu (station)')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_carburant', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Relevé carburant',
                'verbose_name_plural': 'Relevés carburant',
                'ordering': ['-date_releve', '-id'],
            },
        ),
    ]
