# Generated by Django 5.2.10 on 2026-02-08 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0003_rapports_maintenance_carburant_conducteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cout_location',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Coût global ou complément au loyer', max_digits=14, null=True, verbose_name='Coût de location (FCFA)'),
        ),
        migrations.AddField(
            model_name='location',
            name='frais_annexes',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Assurance, entretien, carburant, etc.', max_digits=14, null=True, verbose_name='Frais annexes (FCFA)'),
        ),
        migrations.CreateModel(
            name='ChargeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fret', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Fret (transport international, FCFA)')),
                ('frais_dedouanement', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Frais de dédouanement (FCFA)')),
                ('frais_transitaire', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Frais de service du transitaire (FCFA)')),
                ('cout_total', models.DecimalField(blank=True, decimal_places=0, help_text='Calcul automatique (fret + dédouanement + transitaire) ou saisie manuelle', max_digits=14, null=True, verbose_name="Coût total d'importation (FCFA)")),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_import', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': "Charge d'importation",
                'verbose_name_plural': "Charges d'importation",
                'ordering': ['vehicule', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Contravention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_contravention', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Référence / N° PV')),
                ('montant', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Montant / pénalité (FCFA)')),
                ('lieu', models.CharField(blank=True, max_length=120, verbose_name='Lieu')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraventions', to='flotte.location')),
            ],
            options={
                'verbose_name': 'Contravention',
                'verbose_name_plural': 'Contraventions',
                'ordering': ['location', '-date_contravention', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartieImportee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Coût unitaire (FCFA)')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(blank=True, help_text='Véhicule concerné (optionnel, pour stock général laisser vide)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_importees', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Partie importée',
                'verbose_name_plural': 'Parties importées',
                'ordering': ['vehicule', '-id'],
            },
        ),
    ]
