# Generated by Django 5.2.10 on 2026-02-08 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0004_charges_import_pieces_contraventions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=80, unique=True, verbose_name='Libellé')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de document',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='conducteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='flotte.conducteur', verbose_name='Conducteur assigné'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='date_expiration_assurance',
            field=models.DateField(blank=True, help_text='Pour véhicules non loués : échéance assurance', null=True, verbose_name='Date expiration assurance (véhicule au parc)'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='date_expiration_ct',
            field=models.DateField(blank=True, help_text='Pour véhicules non loués : prochaine échéance contrôle technique', null=True, verbose_name='Date expiration CT (véhicule au parc)'),
        ),
        migrations.AlterField(
            model_name='documentvehicule',
            name='type_document',
            field=models.CharField(blank=True, max_length=80, verbose_name='Type (libre si autre)'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=10, verbose_name='Action')),
                ('model_name', models.CharField(max_length=80, verbose_name='Modèle')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Représentation')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='documentvehicule',
            name='type_document_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_vehicule', to='flotte.typedocument', verbose_name='Type (liste)'),
        ),
    ]
