# Generated by Django 5.2.10 on 2026-02-08 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0006_typedocument_data_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='acquereur_compte',
            field=models.ForeignKey(blank=True, help_text="Si l'acquéreur a un compte FLOTTE (rôle Utilisateur), associez-le pour qu'il voie cette vente dans son espace.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_comme_acquereur', to=settings.AUTH_USER_MODEL, verbose_name='Compte client (acquéreur)'),
        ),
    ]
