# Generated by Django 5.2.10 on 2026-02-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0007_add_vente_acquereur_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvehicule',
            name='fichier',
            field=models.FileField(blank=True, help_text='Document scanné (PDF, image)', max_length=255, null=True, upload_to='documents_vehicule/%Y/%m/', verbose_name='Fichier (document)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fichier',
            field=models.FileField(blank=True, help_text='Facture scannée (PDF)', max_length=255, null=True, upload_to='factures/%Y/%m/', verbose_name='Fichier (PDF)'),
        ),
        migrations.AddField(
            model_name='importdemarche',
            name='fichier',
            field=models.FileField(blank=True, help_text='Document scanné (PV, attestation, etc.)', max_length=255, null=True, upload_to='import_demarches/%Y/%m/', verbose_name='Pièce jointe (document)'),
        ),
    ]
