# Generated by Django 5.2.10 on 2026-02-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0008_add_fichier_facture_document_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Photo du véhicule (JPG, PNG)', max_length=255, upload_to='vehicules_photos/%Y/%m/', verbose_name='Photo')),
                ('angle', models.CharField(choices=[('avant', 'Vue avant'), ('arriere', 'Vue arrière'), ('gauche', 'Vue côté gauche'), ('droit', 'Vue côté droit'), ('interieur_avant', 'Intérieur avant'), ('interieur_arriere', 'Intérieur arrière'), ('moteur', 'Moteur'), ('autre', 'Autre')], default='autre', help_text='Angle de prise de vue', max_length=20, verbose_name='Angle / Vue')),
                ('description', models.CharField(blank=True, help_text='Description optionnelle de la photo', max_length=200, verbose_name='Description')),
                ('est_principale', models.BooleanField(default=False, help_text='Photo principale affichée en premier', verbose_name='Photo principale')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage (plus petit = affiché en premier)", verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Photo véhicule',
                'verbose_name_plural': 'Photos véhicule',
                'ordering': ['vehicule', 'ordre', 'est_principale', '-created_at'],
            },
        ),
    ]
