# Generated by Django 5.2.10 on 2026-02-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0009_add_photo_vehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaliteFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_penalite', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('libelle', models.CharField(help_text='Ex: Retard de paiement, Amende', max_length=200, verbose_name='Libellé')),
                ('montant', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Montant (FCFA)')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalites', to='flotte.facture')),
            ],
            options={
                'verbose_name': 'Pénalité facture',
                'verbose_name_plural': 'Pénalités facture',
                'ordering': ['facture', '-date_penalite', '-id'],
            },
        ),
    ]
