# Generated by Django 5.2.10 on 2026-02-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0010_add_penalite_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contravention',
            name='motif',
            field=models.CharField(blank=True, help_text='Ex: Excès de vitesse, Stationnement interdit, Non-respect de la signalisation', max_length=200, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='contravention',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant à la charge du locataire, ajouté à la facture de location', max_digits=14, null=True, verbose_name='Montant (FCFA)'),
        ),
    ]
