# Generated by Django 5.2.10 on 2026-02-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0011_add_contravention_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='code_ca_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='Code affichage montants CA (haché)'),
        ),
    ]
