# Generated by Django 5.2.10 on 2026-02-27 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0012_add_code_ca_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='proprietaire',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, ce véhicule et ses données associées ne sont visibles que par cet utilisateur (et par les managers / administrateurs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules_flotte', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire (utilisateur)'),
        ),
    ]
