"""URLs FLOTTE."""
from django.urls import path
from . import views

app_name = 'flotte'

urlpatterns = [
    path('', views.FlotteLoginView.as_view(), name='login'),
    path('logout/', views.FlotteLogoutView.as_view(), name='logout'),
    path('mot-de-passe-oublie/', views.FlottePasswordResetView.as_view(), name='password_reset'),
    path('mot-de-passe-oublie/envoye/', views.FlottePasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reinitialiser/<uidb64>/<token>/', views.FlottePasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reinitialiser/termine/', views.FlottePasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # Parc / Véhicules
    path('parc/', views.ParcListView.as_view(), name='parc'),
    path('parc/ajout/', views.VehiculeCreateView.as_view(), name='vehicule_create'),
    path('parc/<int:pk>/', views.vehicule_detail, name='vehicule_detail'),
    path('parc/<int:pk>/modifier/', views.VehiculeUpdateView.as_view(), name='vehicule_update'),
    path('parc/<int:vehicule_pk>/documents/ajout/', views.DocumentVehiculeCreateView.as_view(), name='document_create'),
    path('parc/<int:vehicule_pk>/reparations/ajout/', views.ReparationCreateView.as_view(), name='reparation_create'),
    path('parc/<int:vehicule_pk>/depenses/ajout/', views.DepenseCreateView.as_view(), name='depense_create'),
    path('parc/<int:vehicule_pk>/factures/ajout/', views.FactureCreateView.as_view(), name='facture_create'),
    path('parc/<int:vehicule_pk>/import-demarches/ajout/', views.ImportDemarcheCreateView.as_view(), name='import_demarche_create'),
    path('parc/<int:vehicule_pk>/ventes/ajout/', views.VenteCreateView.as_view(), name='vente_create'),
    path('import-demarches/<int:pk>/modifier/', views.ImportDemarcheUpdateView.as_view(), name='import_demarche_update'),
    path('ventes/<int:pk>/modifier/', views.VenteUpdateView.as_view(), name='vente_update'),
    path('documents/<int:pk>/modifier/', views.DocumentVehiculeUpdateView.as_view(), name='document_update'),
    path('reparations/<int:pk>/modifier/', views.ReparationUpdateView.as_view(), name='reparation_update'),
    path('depenses/<int:pk>/modifier/', views.DepenseUpdateView.as_view(), name='depense_update'),
    path('factures/<int:pk>/modifier/', views.FactureUpdateView.as_view(), name='facture_update'),
    # Location
    path('location/', views.LocationListView.as_view(), name='location_list'),
    path('location/ajout/', views.LocationCreateView.as_view(), name='location_create'),
    path('location/<int:pk>/', views.location_detail, name='location_detail'),
    path('location/<int:pk>/modifier/', views.LocationUpdateView.as_view(), name='location_update'),
    # Autres sections
    path('import/', views.import_list, name='import_list'),
    path('reparations/', views.reparations_list, name='reparations_list'),
    path('documents/', views.documents_list, name='documents_list'),
    path('ventes/', views.ventes_list, name='ventes_list'),
    path('ca/', views.ca_view, name='ca'),
    path('ca/rapport/<int:pk>/', views.rapport_download, name='rapport_download'),
    path('ca/rapport/<int:pk>/modifier/', views.RapportJournalierUpdateView.as_view(), name='rapport_update'),
    path('maintenance/', views.maintenance_list, name='maintenance_list'),
    path('maintenance/ajout/', views.MaintenanceCreateView.as_view(), name='maintenance_create'),
    path('maintenance/<int:pk>/modifier/', views.MaintenanceUpdateView.as_view(), name='maintenance_update'),
    path('carburant/', views.carburant_list, name='carburant_list'),
    path('carburant/ajout/', views.ReleveCarburantCreateView.as_view(), name='carburant_create'),
    path('carburant/<int:pk>/modifier/', views.ReleveCarburantUpdateView.as_view(), name='carburant_update'),
    path('conducteurs/', views.conducteurs_list, name='conducteurs_list'),
    path('conducteurs/ajout/', views.ConducteurCreateView.as_view(), name='conducteur_create'),
    path('conducteurs/<int:pk>/modifier/', views.ConducteurUpdateView.as_view(), name='conducteur_update'),
    # Paramétrage (admin)
    path('parametrage/', views.parametrage_index, name='parametrage_index'),
    path('parametrage/marques/', views.ParametrageMarqueListView.as_view(), name='parametrage_marques'),
    path('parametrage/marques/ajout/', views.MarqueCreateView.as_view(), name='marque_create'),
    path('parametrage/marques/<int:pk>/modifier/', views.MarqueUpdateView.as_view(), name='marque_update'),
    path('parametrage/modeles/', views.ParametrageModeleListView.as_view(), name='parametrage_modeles'),
    path('parametrage/modeles/ajout/', views.ModeleCreateView.as_view(), name='modele_create'),
    path('parametrage/modeles/<int:pk>/modifier/', views.ModeleUpdateView.as_view(), name='modele_update'),
    path('parametrage/carburant/', views.ParametrageCarburantListView.as_view(), name='parametrage_carburant'),
    path('parametrage/carburant/ajout/', views.TypeCarburantCreateView.as_view(), name='type_carburant_create'),
    path('parametrage/carburant/<int:pk>/modifier/', views.TypeCarburantUpdateView.as_view(), name='type_carburant_update'),
    path('parametrage/transmission/', views.ParametrageTransmissionListView.as_view(), name='parametrage_transmission'),
    path('parametrage/transmission/ajout/', views.TypeTransmissionCreateView.as_view(), name='type_transmission_create'),
    path('parametrage/transmission/<int:pk>/modifier/', views.TypeTransmissionUpdateView.as_view(), name='type_transmission_update'),
    path('parametrage/type-vehicule/', views.ParametrageTypeVehiculeListView.as_view(), name='parametrage_type_vehicule'),
    path('parametrage/type-vehicule/ajout/', views.TypeVehiculeCreateView.as_view(), name='type_vehicule_create'),
    path('parametrage/type-vehicule/<int:pk>/modifier/', views.TypeVehiculeUpdateView.as_view(), name='type_vehicule_update'),
    path('parametrage/utilisateurs/', views.parametrage_utilisateurs, name='parametrage_utilisateurs'),
    path('parametrage/utilisateurs/ajout/', views.UserCreateView.as_view(), name='utilisateur_create'),
    path('parametrage/utilisateurs/<int:pk>/modifier/', views.UserUpdateView.as_view(), name='utilisateur_update'),
    # API légère pour formulaire dynamique (modèles par marque)
    path('api/modeles-par-marque/', views.api_modeles_par_marque, name='api_modeles_par_marque'),
]
