# Generated by Django 5.2.10 on 2026-01-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('chart_type', models.CharField(choices=[('line', 'Courbe'), ('bar', 'Histogramme'), ('pie', 'Camembert'), ('doughnut', 'Donut'), ('area', 'Aire')], default='line', max_length=20)),
                ('model_name', models.CharField(max_length=200)),
                ('field_name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('quarter', 'Trimestre'), ('year', 'Année')], default='month', max_length=20)),
                ('operation', models.CharField(blank=True, default='sum', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Graphique',
                'verbose_name_plural': 'Graphiques',
            },
        ),
        migrations.CreateModel(
            name='DashboardGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=200)),
                ('columns', models.JSONField(default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grille de données',
                'verbose_name_plural': 'Grilles de données',
            },
        ),
    ]
