# Generated by Django 5.2.10 on 2026-02-15 13:35

import admin_custom.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_config', models.JSONField(default=admin_custom.models.default_dashboard_metrics_config)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration tableau de bord',
                'verbose_name_plural': 'Configurations tableau de bord',
            },
        ),
    ]
