# Generated by Django 5.2.10 on 2026-02-18 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0002_user_dashboard_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardchart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_charts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardchart',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardchart',
            unique_together={('name', 'user')},
        ),
    ]
